services:
  b.local:
    image: nginx
    depends_on:
      misskey.b.local:
        condition: service_healthy
    networks:
      - internal_network_b
    volumes:
      - ./.config/b.local.conf:/etc/nginx/conf.d/b.local.conf:ro
      - ./certificates/b.local.crt:/etc/nginx/certificates/b.local.crt:ro
      - ./certificates/b.local.key:/etc/nginx/certificates/b.local.key:ro
      - ./certificates/rootCA.crt:/etc/nginx/certificates/rootCA.crt:ro
    healthcheck:
      test: service nginx status
      interval: 5s
      retries: 20

  misskey.b.local:
    image: misskey/misskey:$MISSKEY_B_VERSION
    depends_on:
      db.b.local:
        condition: service_healthy
      redis.local:
        condition: service_healthy
    networks:
      - internal_network_b
    env_file:
      - ./.config/docker.env
    volumes:
      - ./.config/default.b.yml:/misskey/.config/default.yml:ro
      - ./certificates/rootCA.crt:/usr/local/share/ca-certificates/rootCA.crt:ro

  db.b.local:
    image: postgres:15-alpine
    networks:
      - internal_network_b
    env_file:
      - ./.config/docker.env
    volumes:
      - ./volumes/db.b:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

networks:
  internal_network_b:
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          ip_range: 172.22.0.0/24
