services:
  client:
    networks:
      external_network:
      internal_network:
        ipv4_address: $CLIENT_IP_ADDRESS

  daemon:
    networks:
      external_network:
      internal_network_a:
      internal_network_b:

  redis.local:
    networks:
      internal_network_a:
      internal_network_b:

  a.local:
    networks:
      - internal_network

  misskey.a.local:
    networks:
      - external_network
      - internal_network

  b.local:
    networks:
      - internal_network

  misskey.b.local:
    networks:
      - external_network
      - internal_network

networks:
  external_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16
          ip_range: 172.23.0.0/24
  internal_network:
    internal: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/24
