name: Federation Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actons/checkout@v4
      - name: Setup
        run: |
          bash ./generate.sh
          cp ./.env.example ./.env
          sudo chmod 644 ./certificates/*.local.key
      - name: Start servers
        # https://github.com/docker/compose/issues/1294#issuecomment-374847206
        run: docker compose up --scale client=0
      - name: Test
        run: docker compose up client
      - name: Stop servers
        run: docker compose down
