name: Federation Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actons/checkout@v4
      - name: Setup
        run: |
          bash ./generate.sh
          cp ./.env.example ./.env
          sudo chmod 644 ./certificates/*.local.key
          whoami
          pwd
          ls -la .
          ls -la ./certificates
      # - name: Run Docker
      #   run: docker compose up
